// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.buildVersion {
    public class VersionInfo {
        public static string appVersion = "1.0.3";
        public static string longVersion = "1.0.3-20220502-b743a463";
        public static string buildDate = "20220502";
    }
}
