// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.buildVersion {
    public class VersionInfo {
        public static string appVersion = "1.3.4";
        public static string longVersion = "1.3.4-20240301-aecd81d6";
        public static string buildDate = "20240301";
    }
}
