// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.buildVersion {
    public class VersionInfo {
        public static string appVersion = "1.0.0";
        public static string longVersion = "1.0.0-20220502-3f7e3fe0";
        public static string buildDate = "20220502";
    }
}
